-- CreateEnum
CREATE TYPE "ticket_category" AS ENUM ('PAYMENT_ACCOUNT', 'DOCUMENT_AGREEMENT', 'LOAN_REGISTRATION', 'CONSTRUCTION_UPDATE', 'POSSESSION', 'DEFECT_SERVICE', 'COMMUNICATION', 'CANCELLATION_TRANSFER', 'OTHER');

-- AlterTable
ALTER TABLE "tickets" ADD COLUMN     "category" "ticket_category" NOT NULL DEFAULT 'OTHER';

