ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'INDIAMART';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'NINETY_NINE_ACRES';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'JUSTDIAL';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'MAGICBRICKS';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'HOUSING_COM';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'TRADEINDIA';
